import type { Product, Transaction } from "./types"

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Monitor",
    sku: "MON-001",
    category: "Electronics",
    totalStock: 15,
    reorderMin: 5,
    price: 299.99,
    status: "in-stock",
  },
  {
    id: "2",
    name: "Keyboard",
    sku: "KEY-001",
    category: "Electronics",
    totalStock: 3,
    reorderMin: 10,
    price: 79.99,
    status: "low-stock",
  },
  {
    id: "3",
    name: "Mouse",
    sku: "MOUSE-001",
    category: "Electronics",
    totalStock: 0,
    reorderMin: 5,
    price: 29.99,
    status: "out-of-stock",
  },
  {
    id: "4",
    name: "Desk Chair",
    sku: "CHAIR-001",
    category: "Furniture",
    totalStock: 8,
    reorderMin: 3,
    price: 199.99,
    status: "in-stock",
  },
  {
    id: "5",
    name: "Laptop Stand",
    sku: "STAND-001",
    category: "Accessories",
    totalStock: 2,
    reorderMin: 5,
    price: 49.99,
    status: "low-stock",
  },
]

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "T1",
    type: "receipt",
    productId: "1",
    quantity: 50,
    status: "done",
    timestamp: "2024-01-15T10:30:00",
  },
  {
    id: "T2",
    type: "delivery",
    productId: "2",
    quantity: 10,
    status: "ready",
    timestamp: "2024-01-14T14:20:00",
  },
  {
    id: "T3",
    type: "transfer",
    productId: "4",
    quantity: 5,
    status: "done",
    timestamp: "2024-01-13T09:15:00",
  },
  {
    id: "T4",
    type: "adjustment",
    productId: "3",
    quantity: -2,
    status: "done",
    timestamp: "2024-01-12T16:45:00",
  },
]
